// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PCPASimulator {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PCPASimulator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PromptHeadline {
            get {
                return ResourceManager.GetString("PromptHeadline", resourceCulture);
            }
        }
        
        internal static string OptionParseInput {
            get {
                return ResourceManager.GetString("OptionParseInput", resourceCulture);
            }
        }
        
        internal static string OptionReturn {
            get {
                return ResourceManager.GetString("OptionReturn", resourceCulture);
            }
        }
        
        internal static string OptionQuit {
            get {
                return ResourceManager.GetString("OptionQuit", resourceCulture);
            }
        }
        
        internal static string ResultAutomatonNFormat {
            get {
                return ResourceManager.GetString("ResultAutomatonNFormat", resourceCulture);
            }
        }
        
        internal static char TitleBoxBL {
            get {
                object obj = ResourceManager.GetObject("TitleBoxBL", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static char TitleBoxT {
            get {
                object obj = ResourceManager.GetObject("TitleBoxT", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static char TitleBoxBR {
            get {
                object obj = ResourceManager.GetObject("TitleBoxBR", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static char TitleBoxR {
            get {
                object obj = ResourceManager.GetObject("TitleBoxR", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static char TitleBoxL {
            get {
                object obj = ResourceManager.GetObject("TitleBoxL", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static string MenuHeadline {
            get {
                return ResourceManager.GetString("MenuHeadline", resourceCulture);
            }
        }
        
        internal static char TitleBoxB {
            get {
                object obj = ResourceManager.GetObject("TitleBoxB", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static string OptionNewSystem {
            get {
                return ResourceManager.GetString("OptionNewSystem", resourceCulture);
            }
        }
        
        internal static string MenuPromptInput {
            get {
                return ResourceManager.GetString("MenuPromptInput", resourceCulture);
            }
        }
        
        internal static string InputRejected {
            get {
                return ResourceManager.GetString("InputRejected", resourceCulture);
            }
        }
        
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static string ResultLinePrefixFormat {
            get {
                return ResourceManager.GetString("ResultLinePrefixFormat", resourceCulture);
            }
        }
        
        internal static string ResultReachedWithFormat {
            get {
                return ResourceManager.GetString("ResultReachedWithFormat", resourceCulture);
            }
        }
        
        internal static string LexicalError {
            get {
                return ResourceManager.GetString("LexicalError", resourceCulture);
            }
        }
        
        internal static string InputAccepted {
            get {
                return ResourceManager.GetString("InputAccepted", resourceCulture);
            }
        }
        
        internal static string MenuPromptConfigurationFile {
            get {
                return ResourceManager.GetString("MenuPromptConfigurationFile", resourceCulture);
            }
        }
        
        internal static string MenuSelector {
            get {
                return ResourceManager.GetString("MenuSelector", resourceCulture);
            }
        }
        
        internal static string ResultAfterCommunication {
            get {
                return ResourceManager.GetString("ResultAfterCommunication", resourceCulture);
            }
        }
        
        internal static char TitleBoxTR {
            get {
                object obj = ResourceManager.GetObject("TitleBoxTR", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static char TitleBoxTL {
            get {
                object obj = ResourceManager.GetObject("TitleBoxTL", resourceCulture);
                return ((char)(obj));
            }
        }
        
        internal static System.ConsoleColor Color {
            get {
                object obj = ResourceManager.GetObject("Color", resourceCulture);
                return ((System.ConsoleColor)(obj));
            }
        }
        
        internal static string ResultAfterRequestedCommunication {
            get {
                return ResourceManager.GetString("ResultAfterRequestedCommunication", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
    }
}
